name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: full

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: extractions/setup-just@v2
        - name: Print env
          run: just env

        - name: Lint
          run: just --verbose ci-lint
        
        - name: Audit
          run: just audit --deny warnings
        
        - name: Test
          run: just --verbose ci-test
        
        - name: Test auth required
          run: just --verbose ci-auth-required-test
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
