name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: full

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: extractions/setup-just@v2
        - name: Lint
          run: just --verbose ci_lint
        - name: Audit
          run: just audit --deny warnings
        - name: Test
          run: just --verbose ci_test
