name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: extractions/setup-just@v2
        - name: Lint
          run: just --verbose _ci_lint
        
        - name: Test
          run: just --verbose _ci_test
