name: Dispatched System test

permissions:
    issues: write
    actions: read
    checks: read
    statuses: read

on:
    workflow_run:
        workflows: [Fail for testing purposes]
        types: [completed]
        branches: [main]

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: full


jobs:
    create-issue-on-run-failure:

        runs-on: ubuntu-latest
        # You would typically do this
        # if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        # But because CI should not fail we run no matter what (we use continue-on-error)
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run_id: ${{ github.event.workflow_run.id }}

        steps:
            - uses: actions/checkout@v4
            - uses: extractions/setup-just@v2
            - name: Variables for the triggering workflow
              run: |
                echo "run_id=${{ github.event.workflow_run.id }}"
                echo "repo=${{ github.repository }}"
                echo "workflow_run.conclusion=${{ github.event.workflow_run.conclusion }}"
                echo "workflow_run.status=${{ github.event.workflow_run.status }}"
                echo "workflow_run=${{ github.event.workflow_run }}"

            - name: build
              run: |
                just --verbose build --release
                ./target/release/ci-manager --version
                mv ./target/release/ci-manager $(dirname $(which cargo))
                ci-manager --version
            - name: Test of create-issue-from-run
              run: |
                ci-manager --verbosity 4 \
                            --dry-run \
                    create-issue-from-run \
                        --trim-timestamp \
                        --no-duplicate \
                        --kind=other \
                        --repo=${{ github.repository }} \
                        --title="System test create-issue-from-run" \
                        --label="Dispatched system test" \
                        --run-id="${{ env.run_id }}"
                        