name: Fail for testing purposes

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]    

jobs:
    failing-ci-manager-job:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            # Checkout just to produce some typical output
            - uses: actions/checkout@v4
            - name: doesnt fail
              run: echo "this step didn't fail"
            - name: failing step
              run: |
                echo "this step failed because it called exit 1"
                exit 1

    successful-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: successful step
              run: echo "This step ran successfully"
            - name: another successful step
              run: echo "This step also ran successfully"
