name: Release

on:
    - workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Publish
              run: |
                just check-version
                cargo publish --token ${{ secrets.CARGO_PUBLISH_TOKEN }}