name: Release

on:
    - workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: extractions/setup-just@v2
            - name: Publish
              run: |
                just check-version
                cargo publish --token ${{ secrets.CARGO_PUBLISH_TOKEN }}